### ISSUE TITLE
Incorrect save paths with qBittorrent injection

### ISSUE THREAD

**Issue by mmgoodnow** [mmgoodnow/cross-seed#74]

**Comment by ajhorvath20** [comment]
Thanks @mmgoodnow for looking and sorting it out :)

**Comment by mmgoodnow** [comment]
@ajhorvath20 - in this picture, it looks like you have a cross-seed that you added manually or separately from direct injection, right below a cross-seed added by direct injection. And they have the same location? Are there any differences between them, such as one having auto torrent management turned on but the other not?

https://github.com/mmgoodnow/cross-seed/issues/62#issuecomment-841846434 

![](https://user-images.githubusercontent.com/65309559/118405975-36fcdb80-b672-11eb-8299-2b96d90a01e4.png)

**Comment by ajhorvath20** [comment]
I think I found the issue or maybe I am wrong again :)

I have these files added manually into qbittorrent (Torrent Management: Manual) and cross-seed is saying Missing Files. This is not because it was added manually but the tracker file management was different

![image](https://user-images.githubusercontent.com/65309559/122276855-204ddc80-cedd-11eb-8fd0-e5067d9bfee0.png)

E.g. This one was added manually and the location of this file was /data/.torrents/movies/

![image](https://user-images.githubusercontent.com/65309559/122277334-aec25e00-cedd-11eb-9994-03ee7d9b33fb.png)

But the one cross-seed searched and injected had different file management by tracker i.e. /data/.torrents/movies/Movie.2021.1080p.AMZN.WEB-DL.DDP5.1.H.264

![image](https://user-images.githubusercontent.com/65309559/122277533-e7623780-cedd-11eb-8b98-e831f83cd5e7.png)

I hope this helps you to investigate this better :)

**Comment by mmgoodnow** [comment]
Oh, so was this a false-positive match then?

**Comment by mmgoodnow** [comment]
Is this the only torrent you're getting the missing files bug with?

**Comment by ajhorvath20** [comment]
> Oh, so was this a false-positive match then?

Seems like but filename is exaclty same with same folder name but its in subfolder thats why its Missing Files

**Comment by ajhorvath20** [comment]
> Is this the only torrent you're getting the missing files bug with?

No I have a lot, basically every 5th torrent

**Comment by mmgoodnow** [comment]
For these manually added torrents, were they added with any particular content layout? 
![image](https://user-images.githubusercontent.com/9119498/122279026-976f7a80-ceb5-11eb-8d5b-992264c14958.png)

**Comment by ajhorvath20** [comment]
> For these manually added torrents, were they added with any particular content layout?
> ![image](https://user-images.githubusercontent.com/9119498/122279026-976f7a80-ceb5-11eb-8d5b-992264c14958.png)

Don't create subfolder

**Comment by mmgoodnow** [comment]
Curious, are all the broken ones from the same tracker? Is it a scene tracker?

**Comment by ajhorvath20** [comment]
> Curious, are all the broken ones from the same tracker? Is it a scene tracker?

Yes but not all the time, its happening with PTP, and couple other too.

**Comment by ajhorvath20** [comment]
I was just wondering if its possible to deal with this case, I just got few more since yesterday. Thank you

**Comment by mmgoodnow** [comment]
This is my highest priority once I am done with the logging improvements.

**Comment by ajhorvath20** [comment]
> This is my highest priority once I am done with the logging improvements.

Awe thank you so much. Very helpful

**Comment by mmgoodnow** [comment]
@Drazzilb08 does this pattern match any of the false positives you've gotten?

**Comment by Drazzilb08** [comment]
No this doesn't appear to be the same for me. The false positives that I get are the folder structure is typically off. It will be release name as the parent dir, the. A sub dir simply named `_` then the video files. Typically an issue with shows.

**Comment by mmgoodnow** [comment]
@ajhorvath20 at this point I'm pretty stumped. You're still the only person who has reported this; I think I would be able to debug this much more effectively if I had more information about the exact contents of these torrents but I don't want to ask you to post those in GitHub. If you're willing, here is an invite link to the cross-seed discord server I just created: https://discord.gg/KXBSPSNaYT

Maybe we can figure out a solution there.

**Comment by mmgoodnow** [comment]
https://github.com/mmgoodnow/cross-seed/issues/189#issue-1100988108

**Comment by mmgoodnow** [comment]
@byter09 have you noticed any pattern as to when the save path is incorrect?

**Comment by Byter09** [comment]
So far it only happens when the torrent is a single file. So if the file is `name.file`, I typically have Sonarr/Radarr put it in `name/name.file` automatically because of the qBittorrent setting of always creating subfolders.

So when a new torrent gets injected I always have to add `name` to the location path so it correctly finds the file. The injected torrent tries to find the file in `/name.file` but I need `/name/name.file`

I have the config set to find all torrents, which also sets single file torrents to true as well I think. Just in case it has anything to do with that.

**Comment by mmgoodnow** [comment]
v3.3.1

**Comment by mmgoodnow** [comment]
It seems like we have several different boolean variables here, and we have to cover all cases. - 

| `contentLayout` | `autoTMM` | has category | is single file torrent | Works? |
| --- | --- | --- | --- | --- |
| false | false | false | false |
| false | false | false | true |
| false | false | true | false |
| false | false | true | true |
| false | true | false | false |
| false | true | false | true |
| false | true | true | false |
| false | true | true | true |
| true | false | false | false |
| true | false | false | true |
| true | false | true | false |
| true | false | true | true |
| true | true | false | false |
| true | true | false | true |
| true | true | true | false |
| true | true | true | true |

@Byter09 @Muddro1 can you let me which rows you can confirm either work or don't work?

**Comment by Byter09** [comment]
This is my current setup:
`contentLayout`: true (assuming this is the subfolder setting?)
`autoTMM`: false (turned it off cause cross-seed didn't work correctly with it on, but only because my categories had custom paths)
`hasCategory`: unsure, my categories don't have a custom path anymore. It works with and without category, unsure what happens when I change the paths though. I'd prefer not to destroy my setup :P
`single File`: true and false, both work

All in all, I don't know if autoTMM is that important. Assuming you use injections and qBittorrent moves the torrent to its final destination before cross-seed injects, the only thing that matters should be category paths.

I'm curious, do you have all the information available from the original torrent? If so, why not inject new torrents with those exact same settings.

**Comment by TRaSH-** [comment]
After the latest update i noticed that cross-seed torrents doesn't honor the paths from the existing torrents.

I've in the the default save path `/data/torrents/tv` and in that folder i've subfolders `hd` and `uhd` 

cross seed should honor the original path like it used to !

Example: using the latest release.

![image](https://user-images.githubusercontent.com/6155095/155838353-239aab3e-5afc-412f-a3dd-c268727653f0.png)

as you can see the original is using `/data/torrents/tv-hd/`
and the cross seed is using the `/data/torrents/tv/` 

switched back to  `mmgoodnow/cross-seed:version-3.3.0`
and it works like it should.

![image](https://user-images.githubusercontent.com/6155095/155838893-61380611-9d2d-4b41-baeb-3b74a6856c78.png)

Hope this can be fixed in the next update.

**Comment by bakerboy448** [comment]
this is primarily caused by x-seed injection not being compatible with Auto Torrent Management

The workaround seems to be not to use inject and use save with [Qbit Manage](https://github.com/StuffAnThings/qbit_manage)

**Comment by TRaSH-** [comment]
> this is primarily caused by x-seed injection not being compatible with Auto Torrent Management
> 
> The workaround seems to be not to use inject and use save with [Qbit Manage](https://github.com/StuffAnThings/qbit_manage)

If I switch back to the older version it works, so to me if seems a change broke it.

**Comment by mmgoodnow** [comment]
@TRaSH- this should be fixed by v3.3.2. @Byter09 unfortunately for you we're back to the previous behavior which also has a bug but at least it's a preexisting bug. I'll continue to work to find a solution.

**Comment by mmgoodnow** [comment]
At this point it seems to make the most sense to prioritize #144, then maybe take another stab at solving this bug.

**Comment by Byter09** [comment]
>  @Byter09 unfortunately for you we're back to the previous behavior which also has a bug but at least it's a preexisting bug. I'll continue to work to find a solution.
I thank you for your efforts, and I'll simply switch back to default storage instead of forcing folders in the meantime.

**Comment by TRaSH-** [comment]
> > @TRaSH- this should be fixed by v3.3.2. @Byter09 unfortunately for you we're back to the previous behavior which also has a bug but at least it's a preexisting bug. I'll continue to work to find a solution.
> 
> I am now on 3.3.2 and the problem seems to persist.

So it's still not fixed ?

**Comment by muddro1** [comment]
My experience has been it is not fixed. Reverted again to 3.3.0

**Comment by KyleSanderson** [comment]
ATM indeed does not work presently with 3.3.1 (I haven't tried other versions). PTM specifically in their files specify a folder, where it's added to the root, resulting in a double addition. Other trackers do not do this. Fixing the path by hand works, so it's just a minor script issue.

**Comment by mmgoodnow** [comment]
Okay, I've done a lot of testing and iterating. I identified a bug in qBittorrent which I asked about [here](https://github.com/qbittorrent/qBittorrent/discussions/16616) wherein contentLayout does not get respected when you set the skip_checking option to true (very relevant for cross-seeding). I figured out a workaround though. Basically, for any single-file torrents (the ones affected by contentLayout settings) we start them paused and don't skip the checking, then we trigger a force recheck and unpause them. This is not ideal but it works reasonably well. 

Additionally, I added support for auto torrent management. If the source torrent has autoTMM turned on, any cross-seeds of that torrent will have the same category and also have autoTMM turned on. 

I think there may still be a couple corner cases lurking around where my solution may not work but I was not able to test them. Specifically, I think there might be a case where **if you have a multi-file torrent with only one file** (the terms `multi-file torrent` and `single-file torrent` refer to the way the list of data files is encoded inside the torrent file itself, there are two different formats) **and have the content layout set to NoSubfolder, injection may fail.** NoSubfolder is an uncommon configuration though, and multi-file torrents with only one file are rare.

Please test, whoever can. I'll merge #205 in a week and a half or so if I don't hear of any problems.

**Comment by TRaSH-** [comment]
What has been changed since version-3.3.0 that broke it ?

Being it still doesn't work as it should and worked before.

**Comment by mmgoodnow** [comment]
> Being it still doesn't work as it should and worked before.

It didn't fully work before; there was a long standing bug where single file torrents with a content layout of `Subfolder` would get their matches injected to the wrong location. As it turns out, this is actually a bug in qBittorrent, but I didn't realize it at the time.

3.3.1 was an attempt to fix it which broke injection under different circumstances (auto torrent mgmt I think).

The PR I currently have open does a couple things:
- fix regression introduced in 3.3.1
- enable auto tmm on injected matches when the source torrent has it turned on
- work around the qBittorrent bug with injecting single torrents with `Subfolder` content layout

**Comment by TRaSH-** [comment]
Thx for the feedback

Do you mean the issue with some torrents that have a subfolder with a _ ?

But I got the feeling that the changes that have been made now have a bigger impact then the bug that it had before.
Being that it now fails on the most single file torrents.
And before I hardly had any issues with it that is was using the wrong path.

I'll keep a eye on a new update that might fix it revert the issue.
For now it's best to stick to the last working version.
Or don't use cross seed to inject it to Qbittorrent and let Qbt manager handle it so it picks up the correct path

**Comment by mmgoodnow** [comment]
> But I got the feeling that the changes that have been made now have a bigger impact then the bug that it had before.

The old bug affected a qbittorrent configuration that less people use, partially because it had been in cross-seed for a long time and some people had changed their configurations to avoid it. The recent regression affected a configuration more people use.

**Comment by mmgoodnow** [comment]
> Do you mean the issue with some torrents that have a subfolder with a _ ?

No; you can read the early comments of this issue to see.

**Comment by Davo1624** [comment]
> No this doesn't appear to be the same for me. The false positives that I get are the folder structure is typically off. It will be release name as the parent dir, the. A sub dir simply named `_` then the video files. Typically an issue with shows.

I can confirm this is still happening with the `:qbittorrent` image. The original torrent had a flat file structure, meaning there was no folder other than parent folder (so parent folder -> file). Cross-seed identified the file on another tracker but the new tracker has a different file structure (parent folder -> intermediate folder -> file) so when the torrent file is added to my client is results in `error: missing files`

**Comment by Davo1624** [comment]
Happy to do so, just let me know what discord channel I should join.

Regarding your questions:

1) Yes
2) Yes
3) Content layout is set to Original

**Comment by mmgoodnow** [comment]
https://discord.gg/KXBSPSNaYT

**Comment by Davo1624** [comment]
boo

![image](https://user-images.githubusercontent.com/85573606/159078570-e8245950-9260-4a02-9c1b-5c6acee9688c.png)

**Comment by mmgoodnow** [comment]
https://discord.gg/jpbUFzS5Wb

**Comment by TRaSH-** [comment]
> > But I got the feeling that the changes that have been made now have a bigger impact then the bug that it had before.
> 
> The old bug affected a qbittorrent configuration that less people use, partially because it had been in cross-seed for a long time and some people had changed their configurations to avoid it. The recent regression affected a configuration more people use.

might be perhaps just me then (not able to think as a dev perhaps), but why try to fix something that less people use and that you can prevent by changing something in the config. and break something that more people use and you only can fix by running a older version or not using the inject option ?

**Comment by mmgoodnow** [comment]
v3.3.3
